name: Create latest release
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        WITH_V: true
        PRERELEASE: false
        DEFAULT_BUMP: patch

    - name: Remove latest tag and get new tag
      run: |
        if git tag | grep latest; then git push --delete origin latest; fi

    - name: Set tag as an environment variable
      run: |
        echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

    - name: Create release for the new tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release create ${{ env.TAG }} --repo="$GITHUB_REPOSITORY" --title=${{ env.TAG }}  --generate-notes

    - name: Create new latest tag for the release
      run: |
        git tag -f latest
        git push origin --tag
