# example 2: on merge to master from pull request (recommended)
name: Bump version
on:
  pull_request:
    types:
      - closed
    branches:
      - main
env:
  TAG: ""

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        WITH_V: true
        PRERELEASE: false
        DEFAULT_BUMP: patch

    - name: Remove latest tag get new tag just created
      run: |
        if git tag | grep latest; then gp --delete origin latest; fi
        tag=$(git describe --tags --abbrev=0)
        echo "TAG=$tag"

    - name: Create release for the new tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        Tag: ${{ env.TAG }}
      run: gh release create $Tag --repo="$GITHUB_REPOSITORY" --title=$Tag --generate-notes

    - name: Create new latest tag for the release
      run: |
        git tag -f latest
        git push origin --tag