# example 2: on merge to master from pull request (recommended)
name: Bump version
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'

    - name: Set vars
      run: |
        echo "GLOBAL=$GITHUB_SHA" >> $GITHUB_ENV
        echo "JOB=$GITHUB_RUN_ID" >> $GITHUB_ENV

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        WITH_V: true
        PRERELEASE: false
        DEFAULT_BUMP: patch

    - name: Remove latest tag
      run: |
        if git tag | grep latest; then git push --delete origin latest; fi
        tag=$(git describe --tags --abbrev=0)

    - name: Get new tag
      id: get_tag
      run: echo "TAG=$tag" >> $GITHUB_ENV

    - name: Get recent merged branch name
      id: get_branch_name
      uses: tonynguyenit18/github-action-custom-vars@v1
    - run: echo $RECENT_MERGED_BRANCH_NAME
    - run: echo "BRANCH=$RECENT_MERGED_BRANCH_NAME" >> $GITHUB_ENV

    - name: Create release for the new tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release create ${{ env.TAG }}--repo="$GITHUB_REPOSITORY" --title=${{ env.BRANCH }} --generate-notes

    - name: Create new latest tag for the release
      run: |
        git tag -f latest
        git push origin --tag