name: validations
on:
    pull_request:
      types:
        - closed
      branches:
        - main
  
jobs:
  validations:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: badico-cloud-hub/pr-is-rebased@v1
        with:
          # Default branch of repository
          # param default - (github.event.repository.default_branch)
          #default-branch: ''

          # Branch of pull request
          # param default - (github.event.pull_request.head.ref )
          #pull-request-branch: ''
          
          # Token with credentials for repository
          # is required
          gh-token: ${{ secrets.GITHUB_TOKEN }} 
      
          # React of push in default branch
          # param default: false
          #reactive: ''