name: check if PR is rebased
on:
  push:
    branches:
    - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  check-rebase:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: pr-is-rebased
      id: pr-is-rebased
      uses: badico-cloud-hub/pr-is-rebased@v1
      with:
        gh-token: ${{ env.GH_TOKEN }}
        # React of push in default branch
        # param default: false
        reactive: true
    - name: pr number
      run: echo ${{ steps.pr-is-rebased.outputs.pr-number}}
    - name: is rebased
      run: echo ${{ steps.pr-is-rebased.outputs.rebased}}
