on:
  release:
    types:
      - created

jobs:
  tag:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: create latest tag
      run: |
        echo "Drop and readd latest tag"
        if git tag | grep latest; then 
          git tag --delete latest
          git push origin --tag
        fi
        git tag latest
        git push origin --tag