on:
  release:
    types:
      - created

jobs:
  tag:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: create latest tag
      run: |
        git tag -f latest
        git push origin --tag